![knlogo](https://wp.kntu.ac.ir/aliakbarian/ode/images/logo.png)

<a href="https://colab.research.google.com/github/HesamTaherzadeh/Least-square-Optimization-And-Hypothesis-Testing/blob/main/Pre-Statistics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 style="color:Gray"> Least square optimization and hypothesis testing</h1>
<h2 style="color:Gray font'Serif'">Prerequisites(0): Introduction to Linear Algebra </h2>
<h2 style="color:Gray"> Dr. Masoud Mashhadi </h2>
<h3 style="color:Gray"> Amirhesam Taherzadegani </h3>
<h4 style="color:Gray"> Geomatics engineering and geodesy faculty , KNTU </h4>

In [1]:
import numpy as np  
import sympy as sp 

## Transpose

## $ A^{T}_{i,j} = A_{j,i} $

In [4]:
m1 = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [5]:
m1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## $(A + B)^T = A^T + B^T$

In [16]:
np.random.seed(0)
m2 = np.random.randint(1, 10, (3, 3))
m3 = np.random.randint(1, 10, (3, 3))

In [18]:
m3

array([[8, 7, 9],
       [9, 2, 7],
       [8, 8, 9]])

In [17]:
m2

array([[6, 1, 4],
       [4, 8, 4],
       [6, 3, 5]])

In [20]:
(m2 + m3).T

array([[14, 13, 14],
       [ 8, 10, 11],
       [13, 11, 14]])

In [21]:
m2.T + m3.T 

array([[14, 13, 14],
       [ 8, 10, 11],
       [13, 11, 14]])

In [25]:
assert np.all((m2 + m3).T == m2.T + m3.T)

## Trace

## $Trace(A) = \sum{a_{ii}}$ 

In [28]:
m3

array([[8, 7, 9],
       [9, 2, 7],
       [8, 8, 9]])

In [27]:
np.trace(m3)

19

In [34]:
"""
indexing : ndarray[position,index]

slicing : ndarray[position_0 : position_1]

all intervals in [) except in np.linspace
"""
m3[1, 1]

2

In [35]:
m3[1:3, 1:3]

array([[2, 7],
       [8, 9]])

In [29]:
result = 0
for i in range(m3.shape[0]):
    result += m3[i, i]

In [30]:
result

19

# Inverse

## $A^{-1}A = I$

In [56]:
m4 = np.random.randint(1, 10, (10, 10))
m4

array([[2, 1, 5, 8, 4, 3, 8, 3, 1, 1],
       [5, 6, 6, 7, 9, 5, 2, 5, 9, 2],
       [2, 8, 4, 7, 8, 3, 1, 4, 6, 5],
       [5, 7, 5, 5, 4, 5, 5, 9, 5, 4],
       [8, 6, 6, 1, 2, 6, 4, 1, 6, 1],
       [2, 3, 5, 3, 1, 4, 3, 1, 8, 6],
       [1, 3, 8, 3, 3, 4, 4, 3, 4, 5],
       [2, 3, 2, 5, 7, 9, 3, 4, 1, 1],
       [7, 1, 7, 4, 4, 9, 9, 9, 3, 4],
       [3, 1, 9, 9, 4, 9, 3, 9, 5, 4]])

In [57]:
np.linalg.inv(m4)

array([[-0.02042475, -0.08957295,  0.25407075, -0.1855666 ,  0.12746314,
        -0.06621295, -0.18118493, -0.14913752,  0.18832912,  0.06076089],
       [ 0.01646896, -0.06059659, -0.01895776,  0.14815637,  0.05794709,
        -0.0245819 ,  0.05575864,  0.06038387, -0.13542541, -0.0252609 ],
       [-0.00516433,  0.01536946, -0.01724517, -0.04086204,  0.05322192,
        -0.11454898,  0.16954293, -0.05453978, -0.03340157,  0.04965069],
       [ 0.09355497, -0.08862832,  0.11910274, -0.0490139 ,  0.04408898,
         0.02127655, -0.14943494, -0.0423585 , -0.03118468,  0.1066918 ],
       [-0.03409528,  0.10193055,  0.05865557, -0.10707482, -0.05716202,
        -0.06673487,  0.06354759,  0.01056468,  0.10294912, -0.07931806],
       [-0.02934319, -0.03884461, -0.07476376,  0.02024336,  0.02534617,
         0.05830777, -0.00154975,  0.14122105, -0.05436666,  0.02716983],
       [ 0.08911277,  0.04715578, -0.14300987,  0.10183234, -0.05599024,
         0.07002932,  0.0510255 ,  0.05663145

In [58]:
mat_1 = sp.Matrix(m4)

In [59]:
mat_1.inv().evalf()

Matrix([
[ -0.0204247514196122, -0.0895729520619509,   0.254070752445762,  -0.185566602810081,    0.127463141870611, -0.0662129510978861,   -0.181184931818724,  -0.149137516607047,    0.188329117710566,  0.0607608935325358],
[  0.0164689583698639, -0.0605965868290282, -0.0189577558827596,   0.148156367049697,   0.0579470864152201, -0.0245818997889659,   0.0557586439207359,  0.0603838671372178,   -0.135425410019303, -0.0252609019604762],
[-0.00516433174580427,  0.0153694617149427,  -0.017245167872752, -0.0408620366993968,    0.053221922824828,  -0.114548982007758,     0.16954293333972, -0.0545397832221849,  -0.0334015678715011,  0.0496506879271444],
[  0.0935549696081857, -0.0886283235799308,   0.119102739339971, -0.0490139017288922,    0.044088984508937,  0.0212765454383067,   -0.149434935193714, -0.0423584982482977,  -0.0311846763110272,   0.106691802522397],
[ -0.0340952776253842,    0.10193055005875,  0.0586555673106045,  -0.107074816187635,  -0.0571620167697964, -0.0667348732388179

In [60]:
mat_1.charpoly().as_expr()

lambda**10 - 38*lambda**9 - 306*lambda**8 - 1950*lambda**7 - 13224*lambda**6 + 14171*lambda**5 + 212732*lambda**4 + 4180053*lambda**3 + 18512797*lambda**2 + 24918254*lambda + 157333812

# Gauss-Jordan

In [61]:
np.linalg.matrix_rank(m4)

10

In [62]:
gj = sp.Matrix(np.hstack([m4, np.eye(m4.shape[0])]))

In [63]:
gj.rref()[0]

Matrix([
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0,  -0.0204247514196122, -0.0895729520619509,   0.254070752445762,  -0.185566602810081,    0.127463141870611, -0.0662129510978861,   -0.181184931818724,   -0.149137516607047,    0.188329117710566,  0.0607608935325358],
[0, 1, 0, 0, 0, 0, 0, 0, 0, 0,   0.0164689583698639, -0.0605965868290282, -0.0189577558827595,   0.148156367049697,   0.0579470864152202, -0.0245818997889659,   0.0557586439207359,   0.0603838671372178,   -0.135425410019303, -0.0252609019604762],
[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, -0.00516433174580426,  0.0153694617149428, -0.0172451678727521, -0.0408620366993968,    0.053221922824828,  -0.114548982007758,     0.16954293333972,  -0.0545397832221849,  -0.0334015678715012,  0.0496506879271444],
[0, 0, 0, 1, 0, 0, 0, 0, 0, 0,   0.0935549696081857, -0.0886283235799308,   0.119102739339971, -0.0490139017288922,    0.044088984508937,  0.0212765454383067,   -0.149434935193714,  -0.0423584982482977,  -0.0311846763110271,   0.106691802522397],
[0,

In [64]:
np.linalg.inv(m4)

array([[-0.02042475, -0.08957295,  0.25407075, -0.1855666 ,  0.12746314,
        -0.06621295, -0.18118493, -0.14913752,  0.18832912,  0.06076089],
       [ 0.01646896, -0.06059659, -0.01895776,  0.14815637,  0.05794709,
        -0.0245819 ,  0.05575864,  0.06038387, -0.13542541, -0.0252609 ],
       [-0.00516433,  0.01536946, -0.01724517, -0.04086204,  0.05322192,
        -0.11454898,  0.16954293, -0.05453978, -0.03340157,  0.04965069],
       [ 0.09355497, -0.08862832,  0.11910274, -0.0490139 ,  0.04408898,
         0.02127655, -0.14943494, -0.0423585 , -0.03118468,  0.1066918 ],
       [-0.03409528,  0.10193055,  0.05865557, -0.10707482, -0.05716202,
        -0.06673487,  0.06354759,  0.01056468,  0.10294912, -0.07931806],
       [-0.02934319, -0.03884461, -0.07476376,  0.02024336,  0.02534617,
         0.05830777, -0.00154975,  0.14122105, -0.05436666,  0.02716983],
       [ 0.08911277,  0.04715578, -0.14300987,  0.10183234, -0.05599024,
         0.07002932,  0.0510255 ,  0.05663145

<a href="https://www.emathhelp.net/calculators/linear-algebra/reduced-row-echelon-form-rref-caclulator/" style=" background-color: black;
  color: grey;
  border: 2px dashed grey;
  padding: 10px 20px;
  text-align: center;
  text-decoration: none;
  display: inline-block;">Step by step RREF(emathhelp)</a>

## Determinant

## Derivative and integration

## Positive definite, negative definite , semi negative definite , semi positive definite

<h2> A positive definite matrix: if $x^TAx>0$ for all non-zero real vectors x.

A positive semidefinite matrix: if $x^TAx≥0$ for all non-zero real vectors x.

A negative definite matrix: if $x^TAx<0$ for all non-zero real vectors x.

A negative semidefinite matrix: if $x^TAx≤0$ for all non-zero real vectors x.

An indefinite matrix: if there exists non-zero real vectors x,y with $x^TAx>0>y^TAy$.</h2>

## A real non-symmetric matrix is positive definite if and only if $\frac{A+A^T}{2}$ is positive definite.



# Types of matrix multiplications

> ## Hadamard multiplications
$A \circ B =  A \odot B = C$ for $C =[c_{ij}] = [a_{ij}\times b_{ij}]$

<h1  style="color:red"> BE AWARE OF NUMPY BROADCASTING <h1>

> # Vector norms
> ## $\|A\|_1= \sum_{i=1}^n |a_{ij}|: \text{   Manhatan Norm}$
> ## $\|A\|_2= (\sum_{i=1}^n |a_{ij}|^2)^\frac{1}{2} : \text{  Euclidean Norm}$
> ## $ \left\|\mathbf {x} \right\|_{\infty }:=\max _{i}\left|x_{i}\right| : \infty \text{  Norm}$
> ## $ \left\|\mathbf {x} \right\|_{p}:=\left(\sum _{i=1}^{n}\left|x_{i}\right|^{p}\right)^\frac{1}{p}:  \text{Forbinus Norm}$


> # Norms-induced by p-norm
> ## $\|A\|_{1}=\max _{1\leq j\leq n}\sum _{i=1}^{m}|a_{ij}|$ :  the maximum absolute column sum of the matrix;
> ## $\|A\|_{\infty }=\max _{1\leq i\leq m}\sum _{j=1}^{n}|a_{ij}|$ : simply the maximum absolute row sum of the matrix
> ## $\|A\|_{2}={\sqrt {\lambda _{\max }\left(A^{T}A\right)}}=\sigma _{\max }(A).$

> # Entry wise Norm
> ## $\displaystyle \|A\|_{p,p}=\|\mathrm {vec} (A)\|_{p}=\left(\sum _{i=1}^{m}\sum _{j=1}^{n}|a_{ij}|^{p}\right)^{1/p}$

## Linearization

<img src="https://www.cs.utexas.edu/users/flame/laff/alaff-beta/images/Chapter04/FundamentalSpaces.png">

## Null space(Kernel) and left nullspace

## ${\displaystyle {\begin{bmatrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\a_{31}&a_{32}&a_{33}\end{bmatrix}}={\begin{bmatrix}\ell _{11}&0&0\\\ell _{21}&\ell _{22}&0\\\ell _{31}&\ell _{32}&\ell _{33}\end{bmatrix}}{\begin{bmatrix}u_{11}&u_{12}&u_{13}\\0&u_{22}&u_{23}\\0&0&u_{33}\end{bmatrix}}.}$

# without permutation
# $A = LU$

# with permutation
# $A = PLU$

## Cholesky (if and only if your matrix is positive definitive)

## QR

## ${\displaystyle {\begin{aligned}\mathbf {u} _{1}&=\mathbf {a} _{1},&\mathbf {e} _{1}&={\frac {\mathbf {u} _{1}}{\|\mathbf {u} _{1}\|}}\\\mathbf {u} _{2}&=\mathbf {a} _{2}-\operatorname {proj} _{\mathbf {u} _{1}}\mathbf {a} _{2},&\mathbf {e} _{2}&={\frac {\mathbf {u} _{2}}{\|\mathbf {u} _{2}\|}}\\\mathbf {u} _{3}&=\mathbf {a} _{3}-\operatorname {proj} _{\mathbf {u} _{1}}\mathbf {a} _{3}-\operatorname {proj} _{\mathbf {u} _{2}}\mathbf {a} _{3},&\mathbf {e} _{3}&={\frac {\mathbf {u} _{3}}{\|\mathbf {u} _{3}\|}}\\&\;\;\vdots &&\;\;\vdots \\\mathbf {u} _{k}&=\mathbf {a} _{k}-\sum _{j=1}^{k-1}\operatorname {proj} _{\mathbf {u} _{j}}\mathbf {a} _{k},&\mathbf {e} _{k}&={\frac {\mathbf {u} _{k}}{\|\mathbf {u} _{k}\|}}\end{aligned}}}$

# ${\displaystyle Q={\begin{bmatrix}\mathbf {e} _{1}&\cdots &\mathbf {e} _{n}\end{bmatrix}}}$

## ${\displaystyle R={\begin{bmatrix}\langle \mathbf {e} _{1},\mathbf {a} _{1}\rangle &\langle \mathbf {e} _{1},\mathbf {a} _{2}\rangle &\langle \mathbf {e} _{1},\mathbf {a} _{3}\rangle &\cdots \\0&\langle \mathbf {e} _{2},\mathbf {a} _{2}\rangle &\langle \mathbf {e} _{2},\mathbf {a} _{3}\rangle &\cdots \\0&0&\langle \mathbf {e} _{3},\mathbf {a} _{3}\rangle &\cdots \\\vdots &\vdots &\vdots &\ddots \end{bmatrix}}.}$

<img src='https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Eigenvalue_equation.svg/750px-Eigenvalue_equation.svg.png'>

## multiplication of eigenvalues equals the determinant

## $A = USV^T$

## $\Lambda$

## Column space: Since A is rank k, the first k left singular vectors,(the columns of U), provide an orthonormal basis for the column space of A.

## Row space: Similarly, the first k right singular vectors (the columns of V , or the rows of V Transpose), provide an orthonormal basis for the row space of A.

## Null space: The last right singular vectors(the last columns of V , or the last rows of V Transpose), provide an orthonormal basis for the null space of A.

## Pseudo inverse

## $\displaystyle \left[\begin{matrix}0 & 1 & 2 & 3 & 4\\5 & 6 & 7 & 8 & 9\\10 & 11 & 12 & 13 & 14\\15 & 16 & 17 & 18 & 19\\20 & 21 & 22 & 23 & 24\end{matrix}\right]\left[\begin{matrix}x_1\\ x_2\\x_3\\x_4\\x_5\end{matrix}\right] = \left[\begin{matrix}1\\ 2\\3\\4\\5\end{matrix}\right]$